# Generated by Django 4.0 on 2021-12-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_url',
            field=models.URLField(default='https://www.cleverfiles.com/howto/wp-content/uploads/2016/09/File-BMP-icon-300x300.png'),
        ),
    ]
