# Generated by Django 4.0 on 2021-12-19 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_listing_wathchers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='wathchers',
            new_name='watchers',
        ),
    ]
