# Generated by Django 4.0 on 2021-12-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_listing_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='highest',
            field=models.IntegerField(default=1),
        ),
    ]
